server:
  port: ${ENV_PORT:8080}

#clear:
#  all:
#    cache:
#      fixed:
#        rate:

#management:
#  endpoints:
#    web:
#      exposure:
#        exclude: "*"
#  endpoint:
#    shutdown:
#      enabled: true

#default:
#  language: tr

#error:
#  description: error.description.